'use client';
import {useEffect,useMemo,useState} from 'react';
import {Meal} from '../src/domain/types';
import {availableFor,publishMeal,reservedFor,completeMeal} from '../src/domain/mealInventory';
import {loadDashboard,saveMeal,setMealStatus} from '../src/lib/supabase/dashboard';
import {MealBoard} from '../src/components/dashboard/MealBoard';
import {InventorySummary} from '../src/components/dashboard/InventorySummary';
import {MealForm} from '../src/components/meals/MealForm';

function localDate(offset=0){const date=new Date();date.setDate(date.getDate()+offset);return date.toLocaleDateString('sv-SE',{timeZone:'Asia/Taipei'});}
const dates=[{label:'今天',date:localDate(0)},{label:'明天',date:localDate(1)},{label:'後天',date:localDate(2)}];

export default function Home(){
  const [meals,setMeals]=useState<Meal[]>([]);const [inventory,setInventory]=useState<import('../src/domain/types').InventoryItem[]>([]);const [ingredients,setIngredients]=useState<import('../src/domain/types').Ingredient[]>([]);const [householdId,setHouseholdId]=useState('');const [selectedDate,setSelectedDate]=useState(dates[0].date);const [view,setView]=useState<'dashboard'|'inventory'>('dashboard');const [form,setForm]=useState(false);const [notice,setNotice]=useState('');const [loading,setLoading]=useState(true);const [filter,setFilter]=useState('全部');
  useEffect(()=>{loadDashboard().then(data=>{if(data){setMeals(data.meals);setInventory(data.inventory);setIngredients(data.ingredients);setHouseholdId(data.householdId)}}).finally(()=>setLoading(false))},[]);
  const visibleMeals=meals.filter(m=>m.date===selectedDate);
  const save=async(draft:Meal)=>{const result=publishMeal(draft,meals,inventory,ingredients);if(result.error){setNotice(`無法發布：${result.error}`);return}try{const id=householdId?await saveMeal(result.meal,householdId):result.meal.id;setMeals(current=>[...current,{...result.meal,id}]);setNotice('餐點已發布，食材已標記為保留。');setForm(false)}catch(e){setNotice(e instanceof Error?e.message:'發布失敗')}};
  const action=async(meal:Meal)=>{if(meal.status!=='已發布')return;try{const done=completeMeal(meal,inventory);if(householdId)await setMealStatus(meal.id,'已完成',done.meal.ingredients);setMeals(current=>current.map(m=>m.id===meal.id?done.meal:m));setInventory(done.inventory);setNotice(`${meal.title} 已完成，庫存已更新。`)}catch(e){setNotice(e instanceof Error?e.message:'操作失敗')}};
  const rows=useMemo(()=>ingredients.map(i=>({i,total:inventory.find(x=>x.ingredientId===i.id)?.quantity||0,reserved:reservedFor(meals,i.id),available:availableFor(inventory,meals,i.id)})).filter(x=>filter==='全部'||(filter==='不足'?x.available<=x.i.safetyStock:x.reserved>0)),[meals,inventory,ingredients,filter]);
  if(loading)return <main className="auth-page"><div className="auth-card"><p>載入家庭冰箱中…</p></div></main>;
  return <main className="app-shell"><header className="topbar"><div className="brand"><div className="brand-mark">✦</div><div><b>MealCall</b><small>家庭餐桌</small></div></div><div className="header-right"><span className="family-label">鍾家冰箱</span><div className="avatar">E</div></div></header><div className="content">{view==='dashboard'?<><div className="page-heading"><div><span className="eyebrow">MEAL PLAN</span><h1>{dates.find(d=>d.date===selectedDate)?.label}吃什麼？</h1><p>把今天的餐桌，交給家裡的每個人一起決定。</p></div><button className="primary-button" onClick={()=>setForm(true)}>＋ 安排一餐</button></div>{notice&&<div className="notice">✓ {notice}<button onClick={()=>setNotice('')}>×</button></div>}<div className="dashboard-layout"><div><div className="date-tabs">{dates.map(d=><button key={d.date} className={selectedDate===d.date?'active':''} onClick={()=>setSelectedDate(d.date)}>{d.label}<small>{d.date.slice(5).replace('-','/')}</small></button>)}</div><MealBoard meals={visibleMeals} ingredients={ingredients} onAction={action}/></div><InventorySummary ingredients={ingredients} inventory={inventory} meals={meals} onAll={()=>setView('inventory')}/></div></>:<><div className="page-heading compact"><div><button className="back-link" onClick={()=>setView('dashboard')}>← 回到看板</button><h1>全部庫存</h1><p>查看冰箱裡每一項食材的使用狀態。</p></div></div><div className="filter-tabs">{['全部','不足','已保留'].map(x=><button className={filter===x?'active':''} key={x} onClick={()=>setFilter(x)}>{x}</button>)}</div><div className="inventory-table"><div className="table-header"><span>食材</span><span>總庫存</span><span>已保留</span><span>可用量</span><span>安全庫存</span><span>狀態</span></div>{rows.map(({i,total,reserved,available})=><div className="table-row" key={i.id}><span className="food-name">{i.name}</span><span>{total} {i.unit}</span><span>{reserved} {i.unit}</span><span><b>{available}</b> {i.unit}</span><span>{i.safetyStock} {i.unit}</span><span className={available<=i.safetyStock?'warning':'good'}>{available<=i.safetyStock?'需要補貨':'庫存正常'}</span></div>)}</div></>}{form&&<MealForm ingredients={ingredients} onClose={()=>setForm(false)} onSave={save}/>}</div></main>;
}
